config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :bookmarks

      resources :reviews

      resources :crews

      resources :casts

      resources :directors

      resources :actors

      resources :movies

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "movies#index"
  resources :bookmarks
  resources :reviews
  resources :crews
  resources :casts
  resources :directors
  resources :actors
  resources :movies
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cast.rb
class Cast < ApplicationRecord
  # Direct associations

  belongs_to :actor

  belongs_to :movie

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    movie.to_s
  end
end

app/controllers/api/v1/casts_controller.rb
class Api::V1::CastsController < Api::V1::GraphitiController
  def index
    casts = CastResource.all(params)
    respond_with(casts)
  end

  def show
    cast = CastResource.find(params)
    respond_with(cast)
  end

  def create
    cast = CastResource.build(params)

    if cast.save
      render jsonapi: cast, status: :created
    else
      render jsonapi_errors: cast
    end
  end

  def update
    cast = CastResource.find(params)

    if cast.update_attributes
      render jsonapi: cast
    else
      render jsonapi_errors: cast
    end
  end

  def destroy
    cast = CastResource.find(params)

    if cast.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: cast
    end
  end
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  before_action :set_cast, only: %i[show edit update destroy]

  def index
    @q = Cast.ransack(params[:q])
    @casts = @q.result(distinct: true).includes(:movie,
                                                :actor).page(params[:page]).per(10)
  end

  def show; end

  def new
    @cast = Cast.new
  end

  def edit; end

  def create
    @cast = Cast.new(cast_params)

    if @cast.save
      message = "Cast was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @cast, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @cast.update(cast_params)
      redirect_to @cast, notice: "Cast was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @cast.destroy
    message = "Cast was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to casts_url, notice: message
    end
  end

  private

  def set_cast
    @cast = Cast.find(params[:id])
  end

  def cast_params
    params.require(:cast).permit(:movie_id, :actor_id)
  end
end

app/views/casts/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Cast #<%= cast.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Movie</dt>
      <dd>
        <% if @cast.movie.present? %>
          <%= link_to cast.movie, cast.movie %>
        <% end %>
      </dd>

      <dt>Actor</dt>
      <dd>
        <% if @cast.actor.present? %>
          <%= link_to cast.actor, cast.actor %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back cast, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_cast_url(cast), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to cast, method: :delete, data: { confirm: "Do you really want to delete this cast?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(cast.updated_at) %> ago
  </div>
</div>

app/views/casts/_casts_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "casts_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :movie_name_cont, "Movie name contains" %>
    <%= f.text_field :movie_name_cont, :class => "form-control", :placeholder => "Movie name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :actor_name_cont, "Actor name contains" %>
    <%= f.text_field :actor_name_cont, :class => "form-control", :placeholder => "Actor name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/casts" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#casts_filters">
  Show filters
</a>

app/views/casts/_form.html.erb
<% was_validated = cast.errors.any? %>

<%= form_with(model: cast, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% movie_class = "form-control" %>
    <% movie_was_invalid = cast.errors.include?(:movie) %>

    <% if was_validated %>
      <% if movie_was_invalid %>
        <% movie_class << " is-invalid" %>
      <% else %>
        <% movie_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :movie_id %>
    <%= f.collection_select :movie_id, Movie.all, :id, :to_s, {}, class: "form-control" %>
    <% if movie_was_invalid %>
      <% cast.errors.full_messages_for(:movie).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% actor_class = "form-control" %>
    <% actor_was_invalid = cast.errors.include?(:actor) %>

    <% if was_validated %>
      <% if actor_was_invalid %>
        <% actor_class << " is-invalid" %>
      <% else %>
        <% actor_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :actor_id %>
    <%= f.collection_select :actor_id, Actor.all, :id, :to_s, {}, class: "form-control" %>
    <% if actor_was_invalid %>
      <% cast.errors.full_messages_for(:actor).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/casts/_list_item.html.erb
<%= link_to cast, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= cast %>
    <small class="text-muted">
      <%= time_ago_in_words(cast.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/casts/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Cast #<%= @cast.id %>
      </h2>

      <div class="card-body">
        <%= render "form", cast: @cast %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/casts/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Casts

      <%= link_to new_cast_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "casts/casts_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Casts

        <%= link_to new_cast_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @casts, partial: "list_item", as: :cast %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @casts, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/casts/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Cast
      </h2>

      <div class="card-body">
        <%= render "form", cast: @cast %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/casts/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @cast, partial: "card", as: :cast %>
  </div>
</div>